// Generated by CoffeeScript 1.9.3
(function() {
  sinon.stub(window.Backbone, 'sync', function(method, model, options) {
    var callback, callbackWithVersionedArgs, isError, resp, status, xhr;
    model.updatedByRemoteSync = true;
    resp = options.serverResponse || model.toJSON();
    status = 200;
    callback = options.success;
    xhr = $.extend($.Deferred(), {
      status: status,
      response: resp
    });
    isError = typeof options.errorStatus === 'number';
    if (isError) {
      resp.status = status = options.errorStatus;
      callback = options.error;
    }
    callbackWithVersionedArgs = function() {
      if (Backbone.VERSION === '0.9.10') {
        callback(model, resp, options);
      } else if (Backbone.VERSION[0] === '0') {
        callback(resp, status, xhr);
      } else {
        options.xhr = xhr;
        callback(resp);
      }
      if (isError) {
        return xhr.reject();
      } else {
        return xhr.resolve();
      }
    };
    setTimeout(callbackWithVersionedArgs, 0);
    return xhr;
  });

}).call(this);

//# sourceMappingURL=spec_helper.js.map
