// Generated by CoffeeScript 1.6.3
(function() {
  var StickyStorageAdapter;

  StickyStorageAdapter = window.Backbone.storageAdapters.StickyStorageAdapter;

  describe('StickyStorageAdapter', function() {
    describe('creation', function() {
      it('takes a name in its constructor', function() {
        var storage;
        storage = new StickyStorageAdapter('SuperSizedStorage');
        return expect(storage.name).toBe('SuperSizedStorage');
      });
      return it('initializes', function() {
        var storage;
        storage = new StickyStorageAdapter;
        return storage.initialize().done(function() {
          return expect(storage.store instanceof StickyStore).toBe(true);
        });
      });
    });
    return describe('methods', function() {
      it('sets and gets a record', function() {
        var storage;
        storage = new StickyStorageAdapter;
        return storage.initialize().done(function() {
          return storage.setItem('key', {
            foo: 'bar'
          }).done(function() {
            return storage.getItem('key').done(function(item) {
              return expect(item).toEqual({
                foo: 'bar'
              });
            });
          });
        });
      });
      return it('deletes a record', function() {
        var storage;
        storage = new StickyStorageAdapter;
        return storage.initialize().done(function() {
          return storage.setItem('key', {
            foo: 'bar'
          }).done(function() {
            return storage.removeItem('key').done(function() {
              return storage.getItem('key').done(function(item) {
                return expect(item).toBeNull();
              });
            });
          });
        });
      });
    });
  });

}).call(this);
